
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uymmitbvnyfocweettvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5bW1pdGJ2bnlmb2N3ZWV0dHZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3Mzc0MjEsImV4cCI6MjA2MjMxMzQyMX0.l2wvClg5xan7DkweT413ZMdWaFvjomdVwDYOuG1p9gU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
